### ISSUE TITLE
Need to handle error about undefined function in config file

### ISSUE THREAD

**Issue by JhChoy** [HAECHI-LABS/henesis-cli#40]
handlers/transfer.ts
```
exports.execution2 = function...
```

henesis.yaml
```
...
handlers:
  event2:
    event: Transfer(address,address,uint256)
    version: v1
    runtime: tsnode8
    path: ./handlers/transfer.ts
    dep: ./handlers/package.json
    function: transfer
```

So, the situation is that the function name in henesis.yaml and exported function name are different. CLI needs to determine this.

[Current Behavior]
User can deploy, but there is no error occurred. User can only find the error with log at kibana.

[Expected Behavior]
`Cannot find function name transfer` err msg occurred.
